#!/bin/bash
set -eo pipefail

repo_url=$1
src_path=$2
dst_path=$3
set -u

usage() {
    >&2 echo 'usage: git-dl <git-repo-url> <source-path> <dest-path> [git-clone-args...]'
    exit 1
}

[ -n "$repo_url" ] || usage
[ -n "$src_path" ] || usage
[ -n "$dst_path" ] || usage

shift 3

temp_dir=$(mktemp -d git-dl-XXXXX)

trap 'rm -rf $temp_dir' EXIT

git clone --depth 1 "$@" "$repo_url" "$temp_dir"

mv -iv "${temp_dir}/${src_path}" "$dst_path"
